// Starter food library — sourced from Open Food Facts (ODbL licence)
// Common whole foods and athlete staples, macros per 100g unless noted
const STARTER_FOODS = [
  // Proteins
  {name:'Chicken breast (cooked)',    meal:'lunch',   P:31, C:0,  F:3.6},
  {name:'Chicken thigh (cooked)',     meal:'dinner',  P:26, C:0,  F:9},
  {name:'Salmon fillet',             meal:'dinner',  P:25, C:0,  F:13},
  {name:'Tuna (tinned in water)',    meal:'lunch',   P:26, C:0,  F:1},
  {name:'Cod fillet',                meal:'dinner',  P:18, C:0,  F:1},
  {name:'Prawns (cooked)',           meal:'dinner',  P:20, C:0,  F:1},
  {name:'Turkey mince (lean)',       meal:'dinner',  P:29, C:0,  F:7},
  {name:'Beef mince (5% fat)',       meal:'dinner',  P:26, C:0,  F:5},
  {name:'Eggs (2 large)',            meal:'breakfast',P:12, C:0,  F:10},
  {name:'Egg whites (100ml)',        meal:'breakfast',P:11, C:0,  F:0},
  {name:'Cottage cheese (low fat)', meal:'snack',   P:12, C:4,  F:2},
  {name:'Greek yoghurt 0% (170g)',   meal:'breakfast',P:17, C:7,  F:0},
  {name:'Skyr (170g)',               meal:'breakfast',P:17, C:8,  F:0},
  {name:'Quark (200g)',              meal:'snack',   P:24, C:8,  F:0},
  {name:'Whey protein shake',        meal:'snack',   P:25, C:3,  F:2},
  {name:'Edamame (100g)',            meal:'snack',   P:11, C:9,  F:5},
  {name:'Tofu (firm, 100g)',         meal:'lunch',   P:8,  C:2,  F:4},

  // Carbs
  {name:'White rice (cooked, 200g)', meal:'lunch',   P:5,  C:52, F:0},
  {name:'Brown rice (cooked, 200g)', meal:'lunch',   P:5,  C:46, F:2},
  {name:'Oats (dry, 80g)',           meal:'breakfast',P:11, C:54, F:6},
  {name:'Sweet potato (200g)',       meal:'dinner',  P:4,  C:40, F:0},
  {name:'White potato (200g)',       meal:'dinner',  P:4,  C:36, F:0},
  {name:'Sourdough bread (2 slices)',meal:'breakfast',P:8,  C:34, F:2},
  {name:'Wholemeal bread (2 slices)',meal:'breakfast',P:8,  C:30, F:2},
  {name:'Pasta (cooked, 200g)',      meal:'dinner',  P:8,  C:50, F:1},
  {name:'Rice cakes (3)',            meal:'snack',   P:2,  C:22, F:0},
  {name:'Banana (medium)',           meal:'snack',   P:1,  C:27, F:0},
  {name:'Apple (medium)',            meal:'snack',   P:0,  C:25, F:0},
  {name:'Blueberries (100g)',        meal:'snack',   P:1,  C:14, F:0},
  {name:'Strawberries (100g)',       meal:'snack',   P:1,  C:8,  F:0},
  {name:'Medjool dates (2)',         meal:'snack',   P:1,  C:36, F:0},
  {name:'Granola (50g)',             meal:'breakfast',P:5,  C:32, F:8},
  {name:'Quinoa (cooked, 180g)',     meal:'lunch',   P:8,  C:39, F:4},
  {name:'Lentils (cooked, 200g)',    meal:'lunch',   P:18, C:40, F:2},
  {name:'Chickpeas (200g)',          meal:'lunch',   P:14, C:46, F:4},
  {name:'Black beans (200g)',        meal:'lunch',   P:15, C:40, F:2},

  // Fats
  {name:'Avocado (half)',            meal:'lunch',   P:2,  C:4,  F:15},
  {name:'Almond butter (1 tbsp)',    meal:'snack',   P:4,  C:3,  F:9},
  {name:'Peanut butter (1 tbsp)',    meal:'snack',   P:4,  C:3,  F:8},
  {name:'Olive oil (1 tbsp)',        meal:'other',   P:0,  C:0,  F:14},
  {name:'Almonds (30g)',             meal:'snack',   P:6,  C:3,  F:15},
  {name:'Walnuts (30g)',             meal:'snack',   P:5,  C:2,  F:20},
  {name:'Cashews (30g)',             meal:'snack',   P:5,  C:9,  F:13},
  {name:'Feta cheese (50g)',         meal:'lunch',   P:8,  C:1,  F:11},
  {name:'Cheddar (30g)',             meal:'snack',   P:8,  C:0,  F:12},

  // Veg
  {name:'Spinach (80g)',             meal:'lunch',   P:2,  C:1,  F:0},
  {name:'Broccoli (200g)',           meal:'dinner',  P:6,  C:8,  F:0},
  {name:'Green beans (150g)',        meal:'dinner',  P:3,  C:5,  F:0},
  {name:'Kale (80g)',                meal:'lunch',   P:3,  C:4,  F:1},
  {name:'Courgette (200g)',          meal:'dinner',  P:3,  C:5,  F:0},
  {name:'Peppers (1 large)',         meal:'lunch',   P:1,  C:8,  F:0},
  {name:'Mushrooms (100g)',          meal:'breakfast',P:3,  C:1,  F:0},
  {name:'Tomatoes (2 medium)',       meal:'lunch',   P:1,  C:6,  F:0},
  {name:'Cucumber (half)',           meal:'lunch',   P:1,  C:4,  F:0},
  {name:'Mixed salad (80g)',         meal:'lunch',   P:1,  C:2,  F:0},

  // Complete meals
  {name:'Overnight oats (full)',     meal:'breakfast',P:26, C:68, F:8},
  {name:'Scrambled eggs + sourdough',meal:'breakfast',P:27, C:32, F:14},
  {name:'Chicken & rice bowl',       meal:'lunch',   P:33, C:55, F:10},
  {name:'Salmon + sweet potato',     meal:'dinner',  P:34, C:38, F:16},
  {name:'Turkey chilli + rice',      meal:'dinner',  P:36, C:55, F:8},
  {name:'Prawn stir-fry + noodles',  meal:'dinner',  P:30, C:52, F:10},
  {name:'Chicken curry + rice',      meal:'dinner',  P:38, C:60, F:14},
  {name:'Tuna & bean salad',         meal:'lunch',   P:34, C:28, F:12},
  {name:'Salmon & grain bowl',       meal:'lunch',   P:35, C:42, F:18},
  {name:'Greek yoghurt + berries',   meal:'snack',   P:20, C:22, F:5},
  {name:'Ninja Creami (skyr berry)', meal:'other',   P:22, C:38, F:2},
  {name:'Ninja Creami (cookie dough)',meal:'other',  P:20, C:42, F:8},
];
